#!/bin/sh
find . -iname "*.php" | \
xargs xgettext \
--language=PHP 
--indent \
--keyword=__ \
--keyword=_e \
--keyword=esc_html__ \
--keyword=esc_html_e \
--keyword=esc_attr__ \
--keyword=esc_attr_e \
--keyword=_x:2c,1 \
--keyword=__ngettext:1,2 \
-s \
-n \
--from-code=UTF-8 \
-o "languages/affiliates-mailchimp.pot"
